### ISSUE TITLE
Fix YubiKeys not working with new passkey setup

### ISSUE THREAD

**Issue by reesericci** [obl-ong/admin#16]
As of v1.1.0, yubikeys aren't supported due to how passkeys are requested. This could be fixed by adding a new screen, and rewiring how the login flow works.

**Comment by youngchief-btw** [comment]
Could you perhaps elaborate on how we are currently requesting passkeys and how it causes incompatibility with YubiKeys?

**Comment by reesericci** [comment]
Basically YubiKeys aren't discoverable credentials, and because we're not asking for a specific key (say after you type in an email), it isn't picked up.

**Comment by aboutdavid** [comment]
Would it be a bad idea to consider Yubikey OTP?

**Comment by reesericci** [comment]
Yes - YubiKey OTP would require a lot more work on my end and be less secure.

To fix this I just have to ask for an email and then request only the credentials associated with that email.

**Comment by youngchief-btw** [comment]
You could reuse that same email field for it!

**Comment by aboutdavid** [comment]
https://youtu.be/WIRK_pGdIdA

**Comment by reesericci** [comment]
Also for the record, I was completely wrong about YubiKeys not being discoverable. They're just not discoverable by default, but if I set resident keys to required it works fine
