### ISSUE TITLE
Matrix homeserver

### ISSUE THREAD

**Issue by youngchief-btw** [obl-ong/admin#19]
Matrix would be nice to have at matrix.obl.ong for communication between people (not just Hack Club members!). I was thinking we can run Dendrite and bridge to IRC (#18).

**Comment by reesericci** [comment]
I like this idea, do you think you could work on setting this up?

**Comment by youngchief-btw** [comment]
@reesericci Yup! Sure can :)

**Comment by reesericci** [comment]
I think we're going to do forums instead
