### ISSUE TITLE
requesting an existing domain silently fails 

### ISSUE THREAD

**Issue by mrhappyma** [obl-ong/admin#46]
when trying to request a domain that already exists, pressing the request button just does nothing, leaving me lost and confused oh lordy where's my domain 🥴

**Comment by reesericci** [comment]
A flash message should appear with the failure if this happens, surprised it doesn't crash tbh

**Comment by youngchief-btw** [comment]
If we're being honest here, our codebase is really cursed (and always has been) and I'm surprised we don't have a bug that leads to a fatal crash that takes down the server running Obl.ong yet with a kernel panic or something. 😂
