### ISSUE TITLE
Obl.ong is unresolvable and domains are returning NXDOMAIN

### ISSUE THREAD

**Issue by ajs256** [obl-ong/admin#71]
> This is a copy of an announcement that was sent via email to all users 2024-02-05 12:04 PST (UTC-08:00). It may not have been delivered to you correctly.

Hello all,

We are currently aware of an issue causing the obl.ong root domain, and by extension your subdomains, to be unavailable. We are incredibly sorry for this and are doing everything in our power to get the domain back up as soon as possible. PIR, the NIC responsible for the .ong TLD, suspended our domain earlier today for unclear reasons possibly relating to them failing to receive documents we sent earlier last month - we're currently in conversation with them to remove the temporary suspension as soon as possible. We'll update this issue as soon as we hear back from PIR.

Again, we're incredibly sorry for this inconvenience, and thank you for placing your trust in us.

The Obl.ong team

**Comment by reesericci** [comment]
Additionally, I apologize for blasting the v1.3 updates email again to y'all. Our email system is weird and I didn't do enough testing before sending it out. Tracker for replacing that in #62

**Comment by Merlin04** [comment]
Current status: waiting on a response from PIR. 
![image](https://github.com/obl-ong/admin/assets/11800751/9d34be0d-8fb7-4a1c-b883-f2a04794f1be)
![image](https://github.com/obl-ong/admin/assets/11800751/1e5188a5-f0ba-4a07-a79a-8b2113529099)
![image](https://github.com/obl-ong/admin/assets/11800751/81a5445a-2aa1-431f-b827-87e87279643f)
![image](https://github.com/obl-ong/admin/assets/11800751/617d541e-3256-4b5b-b4ef-27fa432b6fca)
![image](https://github.com/obl-ong/admin/assets/11800751/564423ad-1352-43a9-9fa4-6b1360dc593e)

**Comment by Merlin04** [comment]
![Screenshot_20240207-112149.png](https://github.com/obl-ong/admin/assets/11800751/3ab3adfb-21de-4f80-b2f2-f8804c5206d5)

**Comment by reesericci** [comment]
As of 10:07am UTC-6, the ServerHold on the `obl.ong` domain has been lifted and domains have begun to resolve once again!

We once again apologize to our members for this unexpected downtime, and thank them for their patience.

This issue will be updated if any further action is taken regarding this.

![image](https://github.com/obl-ong/admin/assets/19589006/b7c6b934-8aeb-44f8-a8fa-f2afd1951cc6)
